/* eslint-disable */
/* This file is auto-generated by vite-plugin-file-router. */
/* Route structure follows pages/; edits to existing page routes are preserved on regen. */

import type { RouteObject } from 'react-router-dom'

export const routes = [
  /* @file-route "layout:_layout.tsx" */
  {
    lazy: async () => {
      const m = await import("./pages/_layout.tsx")
      return {
        Component: m.default,
      }
    },
    children: [
      /* @file-route "page:index.tsx" */
      {
        index: true,
        lazy: async () => {
          const m = await import("./pages/index.tsx")
          return {
            Component: m.default,
          }
        },
      },
      /* @file-route "page:about.tsx" */
      {
        path: "about",
        lazy: async () => {
          const m = await import("./pages/about.tsx")
          return {
            Component: m.default,
          }
        },
      },
      /* @file-route "layout:dashboard/_layout.tsx" */
      {
        handle: { marker: "snap-dash" },
        path: "dashboard",
        lazy: async () => {
          const m = await import("./pages/dashboard/_layout.tsx")
          return {
            Component: m.default,
          }
        },
        children: [
          /* @file-route "page:dashboard/index.tsx" */
          {
            index: true,
            lazy: async () => {
              const m = await import("./pages/dashboard/index.tsx")
              return {
                Component: m.default,
              }
            },
          },
          /* @file-route "page:dashboard/profile.tsx" */
          {
            path: "profile",
            lazy: async () => {
              const m = await import("./pages/dashboard/profile.tsx")
              return {
                Component: m.default,
              }
            },
          },
          /* @file-route "page:dashboard/settings.tsx" */
          {
            handle: { marker: "snap-settings" },
            path: "settings",
            lazy: async () => {
              const m = await import("./pages/dashboard/settings.tsx")
              return {
                Component: m.default,
              }
            },
          },
        ],
      },
    ],
  }
] satisfies RouteObject[]

export default routes

/* @vite-file-router-manifest eyJ2ZXJzaW9uIjoyLCJyb3V0ZXMiOnsibGF5b3V0Ol9sYXlvdXQudHN4Ijp7InByb3BlcnRpZXMiOnsibGF6eSI6Ik1BbjV2Q2FhUWllcFBfZVR5aU51ZVIifSwiY2hpbGRyZW4iOlsicGFnZTppbmRleC50c3giLCJwYWdlOmFib3V0LnRzeCIsImxheW91dDpkYXNoYm9hcmQvX2xheW91dC50c3giXX0sInBhZ2U6aW5kZXgudHN4Ijp7InByb3BlcnRpZXMiOnsiaW5kZXgiOiJqdk9uLWozMnpUcGhtOE5DSlh4cE1VIiwibGF6eSI6Ijh6OUV3cG5Od0hpZE5XdS1MQTdTd0kifSwiY2hpbGRyZW4iOltdfSwicGFnZTphYm91dC50c3giOnsicHJvcGVydGllcyI6eyJwYXRoIjoiU2d1cVVYSUQydk94bjl1OXQxSzdYdiIsImxhenkiOiI2RnhhVjFyT21iZmpIeHZ0LUZydFNZIn0sImNoaWxkcmVuIjpbXX0sImxheW91dDpkYXNoYm9hcmQvX2xheW91dC50c3giOnsicHJvcGVydGllcyI6eyJwYXRoIjoiM055YXRFbTZsejFNdWxmZkd5RTJueSIsImxhenkiOiItTTZrQm42cEtJSnlSTE5hSjl4UTFhIn0sImNoaWxkcmVuIjpbInBhZ2U6ZGFzaGJvYXJkL2luZGV4LnRzeCIsInBhZ2U6ZGFzaGJvYXJkL3Byb2ZpbGUudHN4IiwicGFnZTpkYXNoYm9hcmQvc2V0dGluZ3MudHN4Il19LCJwYWdlOmRhc2hib2FyZC9pbmRleC50c3giOnsicHJvcGVydGllcyI6eyJpbmRleCI6Imp2T24tajMyelRwaG04TkNKWHhwTVUiLCJsYXp5IjoiSU9aanU2NU14bTUwUUR1U0ZUNmdtNCJ9LCJjaGlsZHJlbiI6W119LCJwYWdlOmRhc2hib2FyZC9wcm9maWxlLnRzeCI6eyJwcm9wZXJ0aWVzIjp7InBhdGgiOiJ4NWg5M1ByQ2xtLVJ5QmRGV0FpMDMxIiwibGF6eSI6InFRZnB0dERqaW9JQnVkc3F2ZmZtdDIifSwiY2hpbGRyZW4iOltdfSwicGFnZTpkYXNoYm9hcmQvc2V0dGluZ3MudHN4Ijp7InByb3BlcnRpZXMiOnsicGF0aCI6InFfV0lLRkNWLTZPNE56LXNkMkxiNzMiLCJsYXp5IjoieV9GN1hJY1VGNWJEbjZ3RDdEZXdHWCJ9LCJjaGlsZHJlbiI6W119fSwiaW1wb3J0cyI6WyJPNEZlV21RY2NFbGl5MGI3QWRDMnpSIl0sInN0YXRlbWVudHMiOltdfQ== */
