/* eslint-disable */
/* This file is auto-generated by vite-plugin-file-router. */
/* Route structure follows pages/; edits to existing page routes are preserved on regen. */

export type RouteMeta = Record<string, string | number | boolean | undefined>

export type FileRoute = {
  path?: string
  index?: boolean
  lazy?: () => Promise<unknown>
  Component?: unknown
  loader?: unknown
  action?: unknown
  ErrorBoundary?: unknown
  shouldRevalidate?: unknown
  handle?: RouteMeta
  children?: FileRoute[]
}

export const routes: FileRoute[] = [
  {
    lazy: async () => {
      const m = await import("./pages/_layout.tsx")
      return {
        Component: m.default,
      }
    },
    children: [
      {
        index: true,
        lazy: async () => {
          const m = await import("./pages/index.tsx")
          return {
            Component: m.default,
          }
        },
      },
      {
        path: "about",
        lazy: async () => {
          const m = await import("./pages/about.tsx")
          return {
            Component: m.default,
          }
        },
      },
      {
        handle: { marker: "snap-dash" },
        path: "dashboard",
        lazy: async () => {
          const m = await import("./pages/dashboard/_layout.tsx")
          return {
            Component: m.default,
          }
        },
children: [
          {
            index: true,
            lazy: async () => {
              const m = await import("./pages/dashboard/index.tsx")
              return {
                Component: m.default,
              }
            },
          },
          {
            path: "profile",
            lazy: async () => {
              const m = await import("./pages/dashboard/profile.tsx")
              return {
                Component: m.default,
              }
            },
          },
          {
            handle: { marker: "snap-settings" },
        path: "settings",
            lazy: async () => {
              const m = await import("./pages/dashboard/settings.tsx")
              return {
                Component: m.default,
              }
            },
          },
        ],
      },
    ],
  },
]

export default routes
