/* eslint-disable */
/* This file is auto-generated by vite-plugin-file-router. */
/* Route structure follows pages/; edits to existing page routes are preserved on regen. */

import type { RouteObject } from 'react-router-dom'

export const routes = [
  /* @file-route "layout:_layout.tsx" */
  {
    handle: { marker: "snap-layout" },
    lazy: async () => {
      const m = await import("./pages/_layout.tsx")
      return {
        Component: m.default,
      }
    },
    children: [
      /* @file-route "page:index.tsx" */
      {
        index: true,
        lazy: async () => {
          const m = await import("./pages/index.tsx")
          return {
            Component: m.default,
          }
        },
      },
      /* @file-route "page:about.tsx" */
      {
        handle: { marker: "snap-about" },
        path: "about",
        lazy: async () => {
          const m = await import("./pages/about.tsx")
          return {
            Component: m.default,
          }
        },
      },
      /* @file-route "page:help.tsx" */
      {
        path: "help",
        lazy: async () => {
          const m = await import("./pages/help.tsx")
          return {
            Component: m.default,
          }
        },
      },
    ],
  }
] satisfies RouteObject[]

export default routes

/* @vite-file-router-manifest eyJ2ZXJzaW9uIjoyLCJyb3V0ZXMiOnsibGF5b3V0Ol9sYXlvdXQudHN4Ijp7InByb3BlcnRpZXMiOnsibGF6eSI6Ik1BbjV2Q2FhUWllcFBfZVR5aU51ZVIifSwiY2hpbGRyZW4iOlsicGFnZTppbmRleC50c3giLCJwYWdlOmFib3V0LnRzeCIsInBhZ2U6aGVscC50c3giXX0sInBhZ2U6aW5kZXgudHN4Ijp7InByb3BlcnRpZXMiOnsiaW5kZXgiOiJqdk9uLWozMnpUcGhtOE5DSlh4cE1VIiwibGF6eSI6Ijh6OUV3cG5Od0hpZE5XdS1MQTdTd0kifSwiY2hpbGRyZW4iOltdfSwicGFnZTphYm91dC50c3giOnsicHJvcGVydGllcyI6eyJwYXRoIjoiU2d1cVVYSUQydk94bjl1OXQxSzdYdiIsImxhenkiOiI2RnhhVjFyT21iZmpIeHZ0LUZydFNZIn0sImNoaWxkcmVuIjpbXX0sInBhZ2U6aGVscC50c3giOnsicHJvcGVydGllcyI6eyJwYXRoIjoiTzdsa3BxUWQwZzltNVR2aGw4UDlvSyIsImxhenkiOiJ2cUxYME1HMUlGUUtGNnRGTWhyQ1NvIn0sImNoaWxkcmVuIjpbXX19LCJpbXBvcnRzIjpbIk80RmVXbVFjY0VsaXkwYjdBZEMyelIiXSwic3RhdGVtZW50cyI6W119 */
