/* eslint-disable */
/* This file is auto-generated by vite-plugin-file-router. */
/* Route structure follows pages/; edits to existing page routes are preserved on regen. */

import type { RouteObject } from 'react-router-dom'

export const routes = [
  /* @file-route "page:index.tsx" */
  {
    path: "/",
    lazy: async () => {
      const m = await import("./pages/index.tsx")
      return {
        Component: m.default,
      }
    },
  },
  /* @file-route "page:about.tsx" */
  {
    handle: { marker: "snap-about" },
    path: "/about",
    lazy: async () => {
      const m = await import("./pages/about.tsx")
      return {
        Component: m.default,
      }
    },
  },
  /* @file-route "page:help.tsx" */
  {
    path: "/help",
    lazy: async () => {
      const m = await import("./pages/help.tsx")
      return {
        Component: m.default,
      }
    },
  }
] satisfies RouteObject[]

export default routes

/* @vite-file-router-manifest eyJ2ZXJzaW9uIjoyLCJyb3V0ZXMiOnsicGFnZTppbmRleC50c3giOnsicHJvcGVydGllcyI6eyJwYXRoIjoiM0VKR01VOWZaQ3hITzNfbnVUUUZMdSIsImxhenkiOiI4ejlFd3BuTndIaWROV3UtTEE3U3dJIn0sImNoaWxkcmVuIjpbXX0sInBhZ2U6YWJvdXQudHN4Ijp7InByb3BlcnRpZXMiOnsicGF0aCI6IjRmd012NF9wUDRURmVxSU1acUR3cDkiLCJsYXp5IjoiNkZ4YVYxck9tYmZqSHh2dC1GcnRTWSJ9LCJjaGlsZHJlbiI6W119LCJwYWdlOmhlbHAudHN4Ijp7InByb3BlcnRpZXMiOnsicGF0aCI6ImM3QnRZTUhJOVQwbVdWSmhKN1lpdFMiLCJsYXp5IjoidnFMWDBNRzFJRlFLRjZ0Rk1ockNTbyJ9LCJjaGlsZHJlbiI6W119fSwiaW1wb3J0cyI6WyJPNEZlV21RY2NFbGl5MGI3QWRDMnpSIl0sInN0YXRlbWVudHMiOltdfQ== */
