import { isCatchAllSegment } from './path-parser'
import type { RouteDiagnostic, RouteNode } from '../types'

interface PageEntry {
  urlPath: string
  filePath: string
}

function collectPages(node: RouteNode, pages: PageEntry[] = []): PageEntry[] {
  for (const child of node.children) {
    if (child.filePath && child.urlPath && !isCatchAllSegment(child.urlPath)) {
      pages.push({ urlPath: child.urlPath, filePath: child.filePath })
    }
    if (child.children.length > 0) collectPages(child, pages)
  }
  return pages
}

function optionalBasePath(urlPath: string): string | null {
  const match = urlPath.match(/^(.*)\/:[^/]+\?$/)
  if (!match) return null
  return match[1] || '/'
}

export function collectRouteDiagnostics(node: RouteNode): RouteDiagnostic[] {
  const diagnostics: RouteDiagnostic[] = []
  const pages = collectPages(node)
  const byPath = new Map<string, PageEntry[]>()

  for (const page of pages) {
    const entries = byPath.get(page.urlPath) ?? []
    entries.push(page)
    byPath.set(page.urlPath, entries)
  }

  for (const [urlPath, entries] of byPath) {
    if (entries.length <= 1) continue
    diagnostics.push({
      level: 'error',
      code: 'duplicate-route',
      message: `Duplicate route "${urlPath}" generated by multiple page files.`,
      routes: entries.map((e) => e.filePath),
    })
  }

  for (const page of pages) {
    const basePath = optionalBasePath(page.urlPath)
    if (!basePath) continue
    const baseEntries = byPath.get(basePath) ?? []
    if (baseEntries.length === 0) continue
    diagnostics.push({
      level: 'warning',
      code: 'optional-route-overlap',
      message: `Optional route "${page.urlPath}" overlaps with "${basePath}".`,
      routes: [page.filePath, ...baseEntries.map((e) => e.filePath)],
    })
  }

  return diagnostics
}
