import path from 'node:path'

import type { GenerateContext, RouteMeta, RouteModuleExports, RouteNode } from '../types'
import { isCatchAllSegment } from '../core/path-parser'
import { attachGeneratedManifest } from './merge-routes'
import { ROUTE_MODULE_EXPORT_NAMES } from '../core/constants'
import { collectUrlPaths } from '../core/scanner'

const GENERATED_BANNER = `/* eslint-disable */
/* This file is auto-generated by vite-plugin-file-router. */
/* Route structure follows pages/; edits to existing page routes are preserved on regen. */
`

function routesFileTail(
  ctx: GenerateContext,
  framework: 'react' | 'vue',
  routeLines: string[],
): string[] {
  const lang = ctx.outputLanguage ?? 'ts'
  const routeType = framework === 'vue' ? 'RouteRecordRaw' : 'RouteObject'
  const routesDecl = 'export const routes = ['
  return [
    routesDecl,
    ...routeLines,
    lang === 'ts' ? `] satisfies ${routeType}[]` : ']',
    '',
    'export default routes',
    '',
  ]
}

export interface ImportRef {
  id: string
  filePath: string
  isLazy: boolean
  /** Named route module bindings co-imported with default (React sync mode). */
  namedBindings?: Array<{ imported: keyof RouteModuleExports; local: string }>
}

function routeMarker(routeId: string, indent: string): string {
  return `${indent}/* @file-route ${JSON.stringify(routeId)} */`
}

function posixRelative(from: string, to: string): string {
  const rel = path.relative(path.dirname(from), to).replace(/\\/g, '/')
  return rel.startsWith('.') ? rel : `./${rel}`
}

function quotedModulePath(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function resolveImportMode(
  node: RouteNode,
  defaultMode: 'lazy' | 'sync',
): 'lazy' | 'sync' {
  return node.importOverride ?? defaultMode
}

function allocImport(
  filePath: string,
  isLazy: boolean,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
): string {
  const key = `${isLazy ? 'lazy' : 'sync'}:${filePath}`
  const existing = imports.get(key)
  if (existing) return existing.id

  const id = syncPageImportName(filePath, usedNames)
  imports.set(key, { id, filePath, isLazy })
  return id
}

const IMPORT_MODE_IN_NAME = /\.(sync|lazy)$/i

function syncPageImportName(filePath: string, usedNames: Set<string>): string {
  let base = path.basename(filePath).replace(/\.(tsx|ts|jsx|js|vue)$/i, '')
  base = base.replace(IMPORT_MODE_IN_NAME, '')
  if (base === 'index') base = 'Index'
  else if (base === '_layout') base = 'Layout'
  else if (base === 'loading') base = 'RouteLoading'
  else if (base === 'error') base = 'RouteError'
  else if (base === 'not-found' || base === '404') base = 'NotFound'
  else if (base.startsWith('[')) base = 'Dynamic'
  else {
    base = base
      .split(/[^a-zA-Z0-9]+/)
      .filter(Boolean)
      .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
      .join('')
  }

  let id = base === 'Layout' || base.startsWith('Route') ? base : `${base}Page`
  let n = 2
  while (usedNames.has(id)) {
    id = `${base}Page${n++}`
  }
  usedNames.add(id)
  return id
}

function pushMultilineField(lines: string[], indent: string, key: string, body: string[]): void {
  if (body.length === 1) {
    lines.push(`${indent}${key}: ${body[0]}`)
    return
  }
  lines.push(`${indent}${key}: ${body[0]}`)
  for (let i = 1; i < body.length; i++) {
    lines.push(`${indent}  ${body[i]}`)
  }
}

function pushReactLazy(
  lines: string[],
  indent: string,
  importPath: string,
  moduleExports?: RouteModuleExports,
  options?: {
    hydrateFallbackId?: string | null
    errorBoundaryId?: string | null
  },
): void {
  const stmt = `${indent}  `
  const field = `${stmt}  `
  const pick = ROUTE_MODULE_EXPORT_NAMES.filter((k) => moduleExports?.[k])
  const modFields = ['Component: m.default', ...pick.map((k) => `${k}: m.${k}`)]

  if (options?.hydrateFallbackId) {
    lines.push(`${indent}HydrateFallback: ${options.hydrateFallbackId},`)
  }
  if (options?.errorBoundaryId) {
    lines.push(`${indent}ErrorBoundary: ${options.errorBoundaryId},`)
  }

  lines.push(`${indent}lazy: async () => {`)
  lines.push(`${stmt}const m = await import(${JSON.stringify(importPath)})`)
  lines.push(`${stmt}return {`)
  for (const f of modFields) lines.push(`${field}${f},`)
  lines.push(`${stmt}}`)
  lines.push(`${indent}},`)
}

function reactHydrateFallbackId(
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  localLoadingPath?: string | null,
  isRootLayout = false,
): string | null {
  const filePath = localLoadingPath ?? (isRootLayout ? ctx.globalLoadingPath : null)
  return filePath ? allocImport(filePath, false, imports, usedNames) : null
}

function reactErrorBoundaryId(
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  localErrorPath?: string | null,
  isRootLayout = false,
): string | null {
  const filePath = localErrorPath ?? (isRootLayout ? ctx.globalErrorPath : null)
  return filePath ? allocImport(filePath, false, imports, usedNames) : null
}

function vueAsyncExtras(
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  localLoading?: string | null,
  localError?: string | null,
) {
  const loadingPath = localLoading ?? ctx.globalLoadingPath ?? null
  const errorPath = localError ?? null
  if (!loadingPath && !errorPath) return undefined
  return { loadingPath, errorPath, outFile: ctx.outFile, imports, usedNames }
}

function vueComponentBody(
  importPath: string,
  extras?: {
    loadingPath?: string | null
    errorPath?: string | null
    outFile?: string
    imports: Map<string, ImportRef>
    usedNames: Set<string>
  },
): { lines: string[]; usesDefineAsyncComponent: boolean } {
  const loading = extras?.loadingPath && extras.outFile
    ? posixRelative(extras.outFile, extras.loadingPath)
    : null
  const error = extras?.errorPath && extras.outFile
    ? posixRelative(extras.outFile, extras.errorPath)
    : null

  if (!loading && !error) {
    return {
      lines: [`() => import(${JSON.stringify(importPath)}),`],
      usesDefineAsyncComponent: false,
    }
  }

  const loadingId = loading
    ? allocImport(extras!.loadingPath!, false, extras!.imports, extras!.usedNames)
    : null
  const errorId = error
    ? allocImport(extras!.errorPath!, false, extras!.imports, extras!.usedNames)
    : null

  const fields = [
    `loader: () => import(${JSON.stringify(importPath)}),`,
    ...(loadingId ? [`loadingComponent: ${loadingId},`] : []),
    ...(errorId ? [`errorComponent: ${errorId},`] : []),
    'delay: 0,',
  ]

  return {
    lines: [
      'defineAsyncComponent({',
      ...fields,
      '}),',
    ],
    usesDefineAsyncComponent: true,
  }
}

function prettifyRouteBlocks(lines: string[]): string[] {
  const out: string[] = []
  for (let i = 0; i < lines.length; i++) {
    out.push(lines[i])
    const cur = lines[i]
    const next = lines[i + 1]
    if (
      cur.trimEnd() === '},'
      && next?.trim() === '{'
      && cur.startsWith('      ')
      && !cur.startsWith('        ')
    ) {
      out.push('')
    }
  }
  return out
}

/** Shared meta-object serializer for React `handle` and Vue `meta` route fields. */
function formatMetaField(
  key: string,
  meta: RouteMeta | undefined,
  indent: string,
): string | undefined {
  if (!meta || Object.keys(meta).length === 0) return undefined
  const entries = Object.entries(meta)
    .filter(([, v]) => v !== undefined)
    .map(([k, v]) => {
      const fieldKey = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)
      const val = JSON.stringify(v)
      if (val === undefined) return null
      return `${fieldKey}: ${val}`
    })
    .filter((entry): entry is string => entry !== null)
  if (entries.length === 0) return undefined
  return `${indent}${key}: { ${entries.join(', ')} },`
}

function formatReactHandle(meta: RouteMeta | undefined, indent: string): string | undefined {
  return formatMetaField('handle', meta, indent)
}

function formatVueMeta(meta: RouteMeta | undefined, indent: string): string | undefined {
  return formatMetaField('meta', meta, indent)
}

/**
 * Generate the `RoutePaths` union type section for type-safe navigation.
 * Returns an empty array when typed routes are disabled or JS output is used.
 */
function typedRoutesSection(
  ctx: GenerateContext,
  root: RouteNode,
): string[] {
  if (!ctx.typedRoutes || ctx.outputLanguage === 'js') return []
  const paths = collectUrlPaths(root)
  const union = paths.length > 0
    ? paths.map((p) => JSON.stringify(p)).join(' | ')
    : 'never'
  return [
    '/** Auto-generated union of all route URL paths. Use for type-safe navigation. */',
    `export type RoutePaths = ${union}`,
    '',
  ]
}

function reactEffectiveModuleExports(
  moduleExports: RouteModuleExports | undefined,
  meta: RouteMeta | undefined,
): RouteModuleExports | undefined {
  if (!moduleExports || !meta || Object.keys(meta).length === 0) return moduleExports
  return { ...moduleExports, handle: false }
}

function indentBlock(lines: string[], pad = '  '): string[] {
  return lines.map((line) => (line === '' ? '' : pad + line))
}

function reactSyncNamedImports(
  filePath: string,
  moduleExports: RouteModuleExports | undefined,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
): string {
  const defaultId = allocImport(filePath, false, imports, usedNames)
  const ref = imports.get(`sync:${filePath}`)!
  if (!moduleExports) return defaultId

  const named = ROUTE_MODULE_EXPORT_NAMES
    .filter((k) => moduleExports[k])
  if (named.length === 0) return defaultId

  ref.namedBindings = named.map((imported) => {
    const suffix = imported.charAt(0).toUpperCase() + imported.slice(1)
    let local = `${defaultId}${suffix}`
    let index = 2
    while (usedNames.has(local)) local = `${defaultId}${suffix}${index++}`
    usedNames.add(local)
    return { imported, local }
  })
  return defaultId
}

function reactSyncModuleFields(filePath: string, imports: Map<string, ImportRef>, indent: string): string[] {
  const bindings = imports.get(`sync:${filePath}`)?.namedBindings ?? []
  return bindings.map(({ imported, local }) => `${indent}${imported}: ${local},`)
}

function reactCatchAllPath(): string {
  return '*'
}

interface LayoutRouteOptions {
  isRootLayout?: boolean
  isTopLevel?: boolean
}

interface RouteEmitter<State> {
  layoutRoute: (
    node: RouteNode,
    ctx: GenerateContext,
    imports: Map<string, ImportRef>,
    usedNames: Set<string>,
    indent: string,
    state: State,
    options?: LayoutRouteOptions,
  ) => string[]
  absoluteLeaf: (
    node: RouteNode,
    ctx: GenerateContext,
    imports: Map<string, ImportRef>,
    usedNames: Set<string>,
    indent: string,
    state: State,
  ) => string[]
  nestedLeaf: (
    node: RouteNode,
    ctx: GenerateContext,
    imports: Map<string, ImportRef>,
    usedNames: Set<string>,
    indent: string,
    state: State,
  ) => string[]
}

/** Top-level route collection: flattens directories, emits absolute leaves. */
function collectRoutes<State>(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  lines: string[],
  state: State,
  fns: RouteEmitter<State>,
): void {
  if (node.layoutPath) {
    lines.push(...fns.layoutRoute(node, ctx, imports, usedNames, indent, state, { isRootLayout: true, isTopLevel: true }))
    return
  }
  for (const child of node.children) {
    if (child.isGroup) {
      if (child.layoutPath) {
        lines.push(...fns.layoutRoute(child, ctx, imports, usedNames, indent, state, { isTopLevel: true }))
      } else {
        collectRoutes(child, ctx, imports, usedNames, indent, lines, state, fns)
      }
    } else if (child.layoutPath) {
      lines.push(...fns.layoutRoute(child, ctx, imports, usedNames, indent, state, { isTopLevel: true }))
    } else if (child.filePath) {
      lines.push(...fns.absoluteLeaf(child, ctx, imports, usedNames, indent, state))
    } else if (child.children.length > 0) {
      collectRoutes(child, ctx, imports, usedNames, indent, lines, state, fns)
    }
  }
}

/** Nested route collection (inside a layout): wraps directories, emits nested leaves. */
function collectNestedRouteLines<State>(
  children: RouteNode[],
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  state: State,
  fns: RouteEmitter<State>,
): string[] {
  const nested: string[] = []
  for (const child of children) {
    if (child.isGroup) {
      if (child.layoutPath) {
        nested.push(...fns.layoutRoute(child, ctx, imports, usedNames, indent, state))
      } else {
        nested.push(...collectNestedRouteLines(child.children, ctx, imports, usedNames, indent, state, fns))
      }
    } else if (child.filePath) {
      nested.push(...fns.nestedLeaf(child, ctx, imports, usedNames, indent, state))
    } else if (child.layoutPath) {
      nested.push(...fns.layoutRoute(child, ctx, imports, usedNames, indent, state))
    } else if (child.children.length) {
      nested.push(...emitDirectoryRoute(child, ctx, imports, usedNames, indent, state, fns))
    }
  }
  return nested
}

/** Directory route with solePage flattening optimization (shared by React/Vue). */
function emitDirectoryRoute<State>(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  state: State,
  fns: RouteEmitter<State>,
): string[] {
  if (!node.path || !node.children.length) return []

  // Flatten a directory that contains only a single non-index page (no layout)
  // into one leaf route with a combined path, e.g. `blog/post` instead of
  // `{ path: 'blog', children: [{ path: 'post' }] }`. Functionally equivalent
  // but reduces nesting in the generated routes file.
  const solePage = node.children.length === 1 && node.children[0].filePath
    ? node.children[0]
    : null
  if (solePage && solePage.path && !solePage.layoutPath) {
    return fns.nestedLeaf({ ...solePage, path: `${node.path}/${solePage.path}` }, ctx, imports, usedNames, indent, state)
  }

  const lines: string[] = []
  const childIndent = indent + '  '
  lines.push(routeMarker(node.routeId, indent))
  lines.push(`${indent}{`)
  lines.push(`${childIndent}path: ${JSON.stringify(node.path)},`)

  const nested = collectNestedRouteLines(node.children, ctx, imports, usedNames, childIndent, state, fns)
  if (nested.length) {
    lines.push(`${childIndent}children: [`)
    lines.push(...indentBlock(nested))
    lines.push(`${childIndent}],`)
  }
  lines.push(`${indent}},`)
  return lines
}

function emitReactLayoutRoute(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  options: LayoutRouteOptions = {},
): string[] {
  const isRootLayout = options.isRootLayout ?? false
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = (node.layoutImportOverride ?? ctx.importMode) === 'lazy'
  const hydrateFallbackId = reactHydrateFallbackId(
    ctx,
    imports,
    usedNames,
    node.loadingPath,
    isRootLayout,
  )
  const errorBoundaryId = reactErrorBoundaryId(
    ctx,
    imports,
    usedNames,
    node.errorPath,
    isRootLayout,
  )
  const moduleExports = node.layoutModuleExports
    ? {
        ...reactEffectiveModuleExports(node.layoutModuleExports, node.meta),
        ...(hydrateFallbackId ? { HydrateFallback: false } : {}),
        ...(errorBoundaryId ? { ErrorBoundary: false } : {}),
      }
    : undefined

  lines.push(routeMarker(node.routeId, indent))
  lines.push(`${indent}{`)
  if (isRootLayout && ctx.baseRoute) {
    lines.push(`${childIndent}path: ${JSON.stringify(ctx.baseRoute)},`)
  } else if (node.path) {
    lines.push(`${childIndent}path: ${JSON.stringify(node.path)},`)
  }

  if (isLazy) {
    pushReactLazy(
      lines,
      childIndent,
      posixRelative(ctx.outFile, node.layoutPath!),
      moduleExports,
      {
        hydrateFallbackId,
        errorBoundaryId,
      },
    )
  } else {
    const id = reactSyncNamedImports(node.layoutPath!, moduleExports, imports, usedNames)
    if (hydrateFallbackId) lines.push(`${childIndent}HydrateFallback: ${hydrateFallbackId},`)
    if (errorBoundaryId) lines.push(`${childIndent}ErrorBoundary: ${errorBoundaryId},`)
    lines.push(`${childIndent}Component: ${id},`)
    lines.push(...reactSyncModuleFields(node.layoutPath!, imports, childIndent))
  }

  const handle = formatReactHandle(node.meta, childIndent)
  if (handle) lines.push(handle)

  const nested = collectNestedRouteLines(node.children, ctx, imports, usedNames, childIndent, undefined, reactEmitter)
  if (nested.length) {
    lines.push(`${childIndent}children: [`)
    lines.push(...indentBlock(nested))
    lines.push(`${childIndent}],`)
  }
  lines.push(`${indent}},`)
  return lines
}

/** Shared React leaf component emission (lazy + sync). */
function emitReactLeafComponent(
  lines: string[],
  childIndent: string,
  node: RouteNode,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  importPath: string,
  isLazy: boolean,
): void {
  if (isLazy) {
    pushReactLazy(lines, childIndent, importPath, reactEffectiveModuleExports(node.moduleExports, node.meta))
  } else {
    const moduleExports = reactEffectiveModuleExports(node.moduleExports, node.meta)
    const id = reactSyncNamedImports(node.filePath!, moduleExports, imports, usedNames)
    lines.push(`${childIndent}Component: ${id},`)
    lines.push(...reactSyncModuleFields(node.filePath!, imports, childIndent))
  }
}

/** Shared React leaf meta emission. */
function emitReactLeafMeta(lines: string[], node: RouteNode, childIndent: string): void {
  const handle = formatReactHandle(node.meta, childIndent)
  if (handle) lines.push(handle)
}

/** Shared Vue leaf component emission (lazy + sync). */
function emitVueLeafComponent(
  lines: string[],
  childIndent: string,
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  importPath: string,
  isLazy: boolean,
  state: { usesDefineAsyncComponent: boolean },
): void {
  if (isLazy) {
    const component = vueComponentBody(
      importPath,
      vueAsyncExtras(ctx, imports, usedNames, node.loadingPath, node.errorPath),
    )
    if (component.usesDefineAsyncComponent) state.usesDefineAsyncComponent = true
    pushMultilineField(lines, childIndent, 'component', component.lines)
  } else {
    const id = allocImport(node.filePath!, false, imports, usedNames)
    lines.push(`${childIndent}component: ${id},`)
  }
}

/** Shared Vue leaf meta + route-block emission. */
function emitVueLeafMeta(lines: string[], node: RouteNode, childIndent: string): void {
  lines.push(...emitVueRouteBlockFields(node, childIndent))
  const meta = formatVueMeta(node.meta, childIndent)
  if (meta) lines.push(meta)
}

function emitReactAbsoluteLeaf(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
): string[] {
  if (!node.filePath) return []
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = resolveImportMode(node, ctx.importMode) === 'lazy'
  const importPath = posixRelative(ctx.outFile, node.filePath)
  const isCatchAll = isCatchAllSegment(node.path ?? '') || node.isNotFound

  lines.push(routeMarker(node.routeId, indent))
  lines.push(`${indent}{`)
  if (isCatchAll) {
    const catchAllPath = node.urlPath.replace(/\*\?$/, '*')
    lines.push(`${childIndent}path: ${JSON.stringify(catchAllPath === '/*' ? '*' : catchAllPath)},`)
  } else {
    lines.push(`${childIndent}path: ${JSON.stringify(node.urlPath === '/' ? '/' : node.urlPath)},`)
  }

  emitReactLeafComponent(lines, childIndent, node, imports, usedNames, importPath, isLazy)
  emitReactLeafMeta(lines, node, childIndent)
  lines.push(`${indent}},`)
  return lines
}

function emitReactLeaf(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
): string[] {
  if (!node.filePath) return []
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = resolveImportMode(node, ctx.importMode) === 'lazy'
  const importPath = posixRelative(ctx.outFile, node.filePath)
  const isIndex = node.path === '' || node.path === null
  const isCatchAll = isCatchAllSegment(node.path ?? '')

  lines.push(routeMarker(node.routeId, indent))
  lines.push(`${indent}{`)

  if (isCatchAll) {
    lines.push(`${childIndent}path: ${JSON.stringify(reactCatchAllPath())},`)
  } else if (!isIndex && node.path) {
    lines.push(`${childIndent}path: ${JSON.stringify(node.path)},`)
  } else if (isIndex) {
    lines.push(`${childIndent}index: true,`)
  }

  emitReactLeafComponent(lines, childIndent, node, imports, usedNames, importPath, isLazy)
  emitReactLeafMeta(lines, node, childIndent)

  lines.push(`${indent}},`)
  return lines
}

function wrapBaseRoute(lines: string[], baseRoute: string, indent: string): string[] {
  if (!baseRoute || lines.length === 0) return lines
  const childIndent = indent + '  '
  return [
    routeMarker(`base:${baseRoute}`, indent),
    `${indent}{`,
    `${childIndent}path: ${JSON.stringify(baseRoute)},`,
    `${childIndent}children: [`,
    ...lines.map((l) => '  ' + l),
    `${childIndent}],`,
    `${indent}},`,
  ]
}

function withFallbackPaths(root: RouteNode, ctx: GenerateContext): GenerateContext {
  return {
    ...ctx,
    globalLoadingPath: ctx.globalLoadingPath ?? root.loadingPath,
    globalErrorPath: ctx.globalErrorPath ?? root.errorPath,
  }
}

interface FrameworkGeneratorConfig<State> {
  emitter: RouteEmitter<State>
  initialState: State
  /** Returns null to skip this import (e.g. lazy imports in React). */
  formatImport: (ref: ImportRef, outFile: string) => string | null
  typeImport: string | null
  runtimeImports: (state: State) => string[]
  framework: 'react' | 'vue'
}

function assembleRoutesFile<State>(
  root: RouteNode,
  ctx: GenerateContext,
  config: FrameworkGeneratorConfig<State>,
): string {
  const resolved = withFallbackPaths(root, ctx)
  const imports = new Map<string, ImportRef>()
  const usedNames = new Set<string>()
  const routeLines: string[] = []
  collectRoutes(root, resolved, imports, usedNames, '  ', routeLines, config.initialState, config.emitter)
  let finalLines = prettifyRouteBlocks(routeLines)
  if (resolved.baseRoute && !root.layoutPath) {
    finalLines = wrapBaseRoute(finalLines, resolved.baseRoute, '  ')
  }

  const importLines: string[] = []
  for (const ref of imports.values()) {
    const line = config.formatImport(ref, ctx.outFile)
    if (line) importLines.push(line)
  }

  const typeImports = ctx.outputLanguage === 'js' || !config.typeImport
    ? []
    : [config.typeImport]
  const runtimeImports = config.runtimeImports(config.initialState)

  const hasHeader = typeImports.length || runtimeImports.length || importLines.length
  return attachGeneratedManifest([
    GENERATED_BANNER,
    ...typeImports,
    ...runtimeImports,
    ...importLines,
    ...(hasHeader ? [''] : []),
    ...typedRoutesSection(ctx, root),
    ...routesFileTail(ctx, config.framework, finalLines),
  ].join('\n'))
}

const reactEmitter: RouteEmitter<void> = {
  layoutRoute: (node, ctx, imports, usedNames, indent, _state, options) =>
    emitReactLayoutRoute(node, ctx, imports, usedNames, indent, options),
  absoluteLeaf: (node, ctx, imports, usedNames, indent, _state) =>
    emitReactAbsoluteLeaf(node, ctx, imports, usedNames, indent),
  nestedLeaf: (node, ctx, imports, usedNames, indent, _state) =>
    emitReactLeaf(node, ctx, imports, usedNames, indent),
}

const vueEmitter: RouteEmitter<{ usesDefineAsyncComponent: boolean }> = {
  layoutRoute: (node, ctx, imports, usedNames, indent, state, options) =>
    emitVueLayoutRoute(node, ctx, imports, usedNames, indent, state, options),
  absoluteLeaf: (node, ctx, imports, usedNames, indent, state) =>
    emitVueAbsoluteLeaf(node, ctx, imports, usedNames, indent, state),
  nestedLeaf: (node, ctx, imports, usedNames, indent, state) =>
    emitVueNestedLeaf(node, ctx, imports, usedNames, indent, state),
}

export function generateReactRoutes(root: RouteNode, ctx: GenerateContext): string {
  return assembleRoutesFile(root, ctx, {
    emitter: reactEmitter,
    initialState: undefined,
    formatImport: (ref, outFile) => {
      if (ref.isLazy) return null
      const rel = posixRelative(outFile, ref.filePath)
      if (ref.namedBindings?.length) {
        const bindings = ref.namedBindings.map(({ imported, local }) => `${imported} as ${local}`)
        return `import { default as ${ref.id}, ${bindings.join(', ')} } from ${quotedModulePath(rel)}`
      }
      return `import ${ref.id} from ${quotedModulePath(rel)}`
    },
    typeImport: `import type { RouteObject } from 'react-router-dom'`,
    runtimeImports: () => [],
    framework: 'react',
  })
}

function emitVueRouteBlockFields(node: RouteNode, indent: string): string[] {
  const block = node.routeBlock
  if (!block) return []
  const lines: string[] = []
  if (block.name) lines.push(`${indent}name: ${JSON.stringify(block.name)},`)
  if (block.alias) {
    const alias = Array.isArray(block.alias)
      ? `[${block.alias.map((a) => JSON.stringify(a)).join(', ')}]`
      : JSON.stringify(block.alias)
    lines.push(`${indent}alias: ${alias},`)
  }
  if (block.props !== undefined) {
    lines.push(
      `${indent}props: ${typeof block.props === 'boolean' ? block.props : JSON.stringify(block.props)},`,
    )
  }
  return lines
}

function vueResolvedPath(node: RouteNode): string {
  if (node.routeBlock?.path) {
    const p = node.routeBlock.path
    return p.startsWith('/') ? p : `/${p}`
  }
  return vueAbsolutePath(node)
}

function vueAbsolutePath(node: RouteNode): string {
  if (isCatchAllSegment(node.path ?? '') || node.isNotFound) {
    const base = node.urlPath.replace(/\/\*\??$/, '')
    return `${base || ''}/:pathMatch(.*)*` || '/:pathMatch(.*)*'
  }
  if (!node.urlPath || node.urlPath === '/') return '/'
  return node.urlPath.startsWith('/') ? node.urlPath : `/${node.urlPath}`
}

function emitVueLayoutRoute(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  state: { usesDefineAsyncComponent: boolean },
  options: { isRootLayout?: boolean; isTopLevel?: boolean } = {},
): string[] {
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = (node.layoutImportOverride ?? ctx.importMode) === 'lazy'
  const isRootLayout = options.isRootLayout ?? false
  const isTopLevel = options.isTopLevel ?? false

  lines.push(routeMarker(node.routeId, indent))
  lines.push(`${indent}{`)
  if (isRootLayout && ctx.baseRoute) {
    lines.push(`${childIndent}path: ${JSON.stringify(ctx.baseRoute)},`)
  } else if (node.routeBlock?.path) {
    const routePath = isTopLevel && !node.routeBlock.path.startsWith('/')
      ? `/${node.routeBlock.path}`
      : node.routeBlock.path
    lines.push(`${childIndent}path: ${JSON.stringify(routePath)},`)
  } else if (node.path) {
    lines.push(`${childIndent}path: ${JSON.stringify(isTopLevel ? vueAbsolutePath(node) : node.path)},`)
  } else if (isTopLevel) {
    lines.push(`${childIndent}path: '/',`)
  } else {
    lines.push(`${childIndent}path: '',`)
  }

  if (isLazy) {
    const component = vueComponentBody(
      posixRelative(ctx.outFile, node.layoutPath!),
      vueAsyncExtras(ctx, imports, usedNames, node.loadingPath, node.errorPath),
    )
    if (component.usesDefineAsyncComponent) state.usesDefineAsyncComponent = true
    pushMultilineField(lines, childIndent, 'component', component.lines)
  } else {
    const id = allocImport(node.layoutPath!, false, imports, usedNames)
    lines.push(`${childIndent}component: ${id},`)
  }

  lines.push(...emitVueRouteBlockFields(node, childIndent))
  const meta = formatVueMeta(node.meta, childIndent)
  if (meta) lines.push(meta)

  const nested = collectNestedRouteLines(node.children, ctx, imports, usedNames, childIndent, state, vueEmitter)
  if (nested.length) {
    lines.push(`${childIndent}children: [`)
    lines.push(...indentBlock(nested))
    lines.push(`${childIndent}],`)
  }
  lines.push(`${indent}},`)
  return lines
}

function emitVueNestedLeaf(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  state: { usesDefineAsyncComponent: boolean },
): string[] {
  if (!node.filePath) return []
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = resolveImportMode(node, ctx.importMode) === 'lazy'
  const importPath = posixRelative(ctx.outFile, node.filePath)
  const isIndex = !node.path || node.path === ''
  const isCatchAll = isCatchAllSegment(node.path ?? '') || /\/\*\??$/.test(node.path ?? '')

  lines.push(routeMarker(node.routeId, indent))
  lines.push(`${indent}{`)
  if (isCatchAll) {
    const rawPath = node.path ?? '*'
    const base = rawPath.replace(/\/?\*\??$/, '')
    lines.push(`${childIndent}path: ${JSON.stringify(base ? `${base}/:pathMatch(.*)*` : ':pathMatch(.*)*')},`)
  } else if (isIndex) {
    lines.push(`${childIndent}path: '',`)
  } else {
    lines.push(`${childIndent}path: ${JSON.stringify(node.routeBlock?.path ?? node.path)},`)
  }

  emitVueLeafComponent(lines, childIndent, node, ctx, imports, usedNames, importPath, isLazy, state)
  emitVueLeafMeta(lines, node, childIndent)
  lines.push(`${indent}},`)
  return lines
}

function emitVueAbsoluteLeaf(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  state: { usesDefineAsyncComponent: boolean },
): string[] {
  if (!node.filePath) return []
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = resolveImportMode(node, ctx.importMode) === 'lazy'
  const importPath = posixRelative(ctx.outFile, node.filePath)

  lines.push(routeMarker(node.routeId, indent))
  lines.push(`${indent}{`)
  lines.push(`${childIndent}path: ${JSON.stringify(vueResolvedPath(node))},`)

  emitVueLeafComponent(lines, childIndent, node, ctx, imports, usedNames, importPath, isLazy, state)
  emitVueLeafMeta(lines, node, childIndent)
  lines.push(`${indent}},`)
  return lines
}

export function generateVueRoutes(root: RouteNode, ctx: GenerateContext): string {
  return assembleRoutesFile(root, ctx, {
    emitter: vueEmitter,
    initialState: { usesDefineAsyncComponent: false },
    formatImport: (ref, outFile) => {
      if (ref.isLazy) return null
      return `import ${ref.id} from ${quotedModulePath(posixRelative(outFile, ref.filePath))}`
    },
    typeImport: `import type { RouteRecordRaw } from 'vue-router'`,
    runtimeImports: (state) =>
      state.usesDefineAsyncComponent ? [`import { defineAsyncComponent } from 'vue'`] : [],
    framework: 'vue',
  })
}
