import path from 'node:path'

import type { GenerateContext, RouteMeta, RouteModuleExports, RouteNode } from '../types'
import { isCatchAllSegment } from '../core/path-parser'
import {
  REACT_TYPES,
  VUE_TYPES,
} from './generated-prelude'

const MODULE_EXPORT_NAMES = ['loader', 'action', 'ErrorBoundary', 'shouldRevalidate', 'handle'] as const

const ROUTE_LOADING_ID = 'RouteLoading'
const ROUTE_ERROR_ID = 'RouteError'

const GENERATED_BANNER = `/* eslint-disable */
/* This file is auto-generated by vite-plugin-file-router. */
/* Route structure follows pages/; edits to existing page routes are preserved on regen. */
`

function routesFileTail(
  ctx: GenerateContext,
  framework: 'react' | 'vue',
  routeLines: string[],
): string[] {
  const lang = ctx.outputLanguage ?? 'ts'
  const types = lang === 'ts'
    ? [framework === 'vue' ? VUE_TYPES : REACT_TYPES, '']
    : []
  const routesDecl = lang === 'ts'
    ? 'export const routes: FileRoute[] = ['
    : 'export const routes = ['
  return [
    ...types,
    routesDecl,
    ...routeLines,
    ']',
    '',
    'export default routes',
    '',
  ]
}

export interface ImportRef {
  id: string
  filePath: string
  isLazy: boolean
  /** Named route module bindings co-imported with default (React sync mode). */
  namedBindings?: Array<keyof RouteModuleExports>
}

function posixRelative(from: string, to: string): string {
  const rel = path.relative(path.dirname(from), to).replace(/\\/g, '/')
  return rel.startsWith('.') ? rel : `./${rel}`
}

function resolveImportMode(
  node: RouteNode,
  defaultMode: 'lazy' | 'sync',
): 'lazy' | 'sync' {
  return node.importOverride ?? defaultMode
}

function allocImport(
  filePath: string,
  isLazy: boolean,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
): string {
  const key = `${isLazy ? 'lazy' : 'sync'}:${filePath}`
  const existing = imports.get(key)
  if (existing) return existing.id

  const id = syncPageImportName(filePath, usedNames)
  imports.set(key, { id, filePath, isLazy })
  return id
}

const IMPORT_MODE_IN_NAME = /\.(sync|lazy)$/i

function syncPageImportName(filePath: string, usedNames: Set<string>): string {
  let base = path.basename(filePath).replace(/\.(tsx|ts|jsx|js|vue)$/i, '')
  base = base.replace(IMPORT_MODE_IN_NAME, '')
  if (base === 'index') base = 'Index'
  else if (base === '_layout') base = 'Layout'
  else if (base === 'not-found' || base === '404') base = 'NotFound'
  else if (base.startsWith('[')) base = 'Dynamic'
  else {
    base = base
      .split(/[^a-zA-Z0-9]+/)
      .filter(Boolean)
      .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
      .join('')
  }

  let id = base === 'Layout' ? 'Layout' : `${base}Page`
  let n = 2
  while (usedNames.has(id)) {
    id = `${base}Page${n++}`
  }
  usedNames.add(id)
  return id
}

function pushMultilineField(lines: string[], indent: string, key: string, body: string[]): void {
  if (body.length === 1) {
    lines.push(`${indent}${key}: ${body[0]}`)
    return
  }
  lines.push(`${indent}${key}: ${body[0]}`)
  for (let i = 1; i < body.length; i++) {
    lines.push(`${indent}  ${body[i]}`)
  }
}

function pushReactLazy(
  lines: string[],
  indent: string,
  importPath: string,
  moduleExports?: RouteModuleExports,
  options?: {
    hydrateFallbackId?: string | null
    errorBoundaryId?: string | null
  },
): void {
  const stmt = `${indent}  `
  const field = `${stmt}  `
  const pick = MODULE_EXPORT_NAMES.filter((k) => moduleExports?.[k])
  const modFields = ['Component: m.default', ...pick.map((k) => `${k}: m.${k}`)]

  if (options?.hydrateFallbackId) {
    lines.push(`${indent}HydrateFallback: ${options.hydrateFallbackId},`)
  }
  if (options?.errorBoundaryId) {
    lines.push(`${indent}ErrorBoundary: ${options.errorBoundaryId},`)
  }

  lines.push(`${indent}lazy: async () => {`)
  lines.push(`${stmt}const m = await import(${JSON.stringify(importPath)})`)
  lines.push(`${stmt}return {`)
  for (const f of modFields) lines.push(`${field}${f},`)
  lines.push(`${stmt}}`)
  lines.push(`${indent}},`)
}

function reactHydrateFallbackId(
  ctx: GenerateContext,
  localLoadingPath?: string | null,
  isRootLayout = false,
): string | null {
  if (localLoadingPath) return ROUTE_LOADING_ID
  if (isRootLayout && ctx.globalLoadingPath) return ROUTE_LOADING_ID
  return null
}

function reactErrorBoundaryId(
  _ctx: GenerateContext,
  localErrorPath?: string | null,
): string | null {
  if (localErrorPath) return ROUTE_ERROR_ID
  return null
}

function reactFallbackImportLines(ctx: GenerateContext): string[] {
  const lines: string[] = []
  if (ctx.globalLoadingPath) {
    lines.push(`import ${ROUTE_LOADING_ID} from '${posixRelative(ctx.outFile, ctx.globalLoadingPath)}'`)
  }
  if (ctx.globalErrorPath) {
    lines.push(`import ${ROUTE_ERROR_ID} from '${posixRelative(ctx.outFile, ctx.globalErrorPath)}'`)
  }
  return lines
}

function vueAsyncExtras(
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  localLoading?: string | null,
  localError?: string | null,
) {
  const loadingPath = localLoading ?? ctx.globalLoadingPath ?? null
  const errorPath = localError ?? null
  if (!loadingPath && !errorPath) return undefined
  return { loadingPath, errorPath, outFile: ctx.outFile, imports, usedNames }
}

function vueComponentBody(
  importPath: string,
  extras?: {
    loadingPath?: string | null
    errorPath?: string | null
    outFile?: string
    imports: Map<string, ImportRef>
    usedNames: Set<string>
  },
): { lines: string[]; usesDefineAsyncComponent: boolean } {
  const loading = extras?.loadingPath && extras.outFile
    ? posixRelative(extras.outFile, extras.loadingPath)
    : null
  const error = extras?.errorPath && extras.outFile
    ? posixRelative(extras.outFile, extras.errorPath)
    : null

  if (!loading && !error) {
    return {
      lines: [`() => import(${JSON.stringify(importPath)}),`],
      usesDefineAsyncComponent: false,
    }
  }

  const loadingId = loading
    ? allocImport(extras!.loadingPath!, false, extras!.imports, extras!.usedNames)
    : null
  const errorId = error
    ? allocImport(extras!.errorPath!, false, extras!.imports, extras!.usedNames)
    : null

  const fields = [
    `loader: () => import(${JSON.stringify(importPath)}),`,
    ...(loadingId ? [`loadingComponent: ${loadingId},`] : []),
    ...(errorId ? [`errorComponent: ${errorId},`] : []),
    'delay: 0,',
  ]

  return {
    lines: [
      'defineAsyncComponent({',
      ...fields,
      '}),',
    ],
    usesDefineAsyncComponent: true,
  }
}

function prettifyRouteBlocks(lines: string[]): string[] {
  const out: string[] = []
  for (let i = 0; i < lines.length; i++) {
    out.push(lines[i])
    const cur = lines[i]
    const next = lines[i + 1]
    if (
      cur.trimEnd() === '},'
      && next?.trim() === '{'
      && cur.startsWith('      ')
      && !cur.startsWith('        ')
    ) {
      out.push('')
    }
  }
  return out
}

function formatReactHandle(meta: RouteMeta | undefined, indent: string): string | undefined {
  if (!meta || Object.keys(meta).length === 0) return undefined
  const entries = Object.entries(meta)
    .filter(([, v]) => v !== undefined)
    .map(([k, v]) => {
      const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)
      const val = typeof v === 'string' ? JSON.stringify(v) : String(v)
      return `${key}: ${val}`
    })
  if (entries.length === 0) return undefined
  return `${indent}handle: { ${entries.join(', ')} },`
}

function formatVueMeta(meta: RouteMeta | undefined, indent: string): string | undefined {
  if (!meta || Object.keys(meta).length === 0) return undefined
  const entries = Object.entries(meta)
    .filter(([, v]) => v !== undefined)
    .map(([k, v]) => {
      const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)
      const val = typeof v === 'string' ? JSON.stringify(v) : String(v)
      return `${key}: ${val}`
    })
  if (entries.length === 0) return undefined
  return `${indent}meta: { ${entries.join(', ')} },`
}

function indentBlock(lines: string[], pad = '  '): string[] {
  return lines.map((line) => (line === '' ? '' : pad + line))
}

function reactSyncNamedImports(
  filePath: string,
  moduleExports: RouteModuleExports | undefined,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
): string {
  const defaultId = allocImport(filePath, false, imports, usedNames)
  const ref = imports.get(`sync:${filePath}`)!
  if (!moduleExports) return defaultId

  const named = (['loader', 'action', 'ErrorBoundary', 'shouldRevalidate', 'handle'] as const)
    .filter((k) => moduleExports[k])
  if (named.length === 0) return defaultId

  ref.namedBindings = [...named]
  return defaultId
}

function reactSyncModuleShorthand(
  moduleExports: RouteModuleExports | undefined,
  indent: string,
): string[] {
  if (!moduleExports) return []
  const names = (['loader', 'action', 'ErrorBoundary', 'shouldRevalidate', 'handle'] as const)
    .filter((k) => moduleExports[k])
  if (names.length === 0) return []
  return [`${indent}${names.join(`,\n${indent}`)},`]
}

function reactCatchAllPath(): string {
  return '*'
}

function collectReactRoutes(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  lines: string[],
): void {
  if (node.layoutPath) {
    lines.push(...emitReactLayoutRoute(node, ctx, imports, usedNames, indent, true))
    return
  }

  for (const child of node.children) {
    if (child.isGroup) {
      if (child.layoutPath) {
        lines.push(...emitReactLayoutRoute(child, ctx, imports, usedNames, indent))
      } else {
        collectReactRoutes(child, ctx, imports, usedNames, indent, lines)
      }
    } else if (child.layoutPath) {
      lines.push(...emitReactLayoutRoute(child, ctx, imports, usedNames, indent))
    } else if (child.filePath) {
      lines.push(...emitReactAbsoluteLeaf(child, ctx, imports, usedNames, indent))
    } else if (child.children.length > 0) {
      collectReactRoutes(child, ctx, imports, usedNames, indent, lines)
    }
  }
}

function emitReactLayoutRoute(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  isRootLayout = false,
): string[] {
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = ctx.importMode === 'lazy'

  lines.push(`${indent}{`)
  if (node.path) {
    lines.push(`${childIndent}path: ${JSON.stringify(node.path)},`)
  }

  if (isLazy) {
    pushReactLazy(
      lines,
      childIndent,
      posixRelative(ctx.outFile, node.layoutPath!),
      node.layoutModuleExports,
      {
        hydrateFallbackId: reactHydrateFallbackId(ctx, node.loadingPath, isRootLayout),
        errorBoundaryId: reactErrorBoundaryId(ctx, node.errorPath),
      },
    )
  } else {
    const id = reactSyncNamedImports(node.layoutPath!, node.layoutModuleExports, imports, usedNames)
    lines.push(`${childIndent}Component: ${id},`)
    lines.push(...reactSyncModuleShorthand(node.layoutModuleExports, childIndent))
  }

  const nested = collectReactNestedRouteLines(node.children, ctx, imports, usedNames, childIndent)
  if (nested.length) {
    lines.push(`${childIndent}children: [`)
    lines.push(...indentBlock(nested))
    lines.push(`${childIndent}],`)
  }
  lines.push(`${indent}},`)
  return lines
}

function emitReactDirectoryRoute(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
): string[] {
  if (!node.path || !node.children.length) return []

  const solePage = node.children.length === 1 && node.children[0].filePath
    ? node.children[0]
    : null
  if (solePage?.path && !solePage.layoutPath) {
    return emitReactNestedLeaf({ ...solePage, path: `${node.path}/${solePage.path}` }, ctx, imports, usedNames, indent)
  }

  const lines: string[] = []
  const childIndent = indent + '  '
  lines.push(`${indent}{`)
  lines.push(`${childIndent}path: ${JSON.stringify(node.path)},`)

  const nested = collectReactNestedRouteLines(node.children, ctx, imports, usedNames, childIndent)
  if (nested.length) {
    lines.push(`${childIndent}children: [`)
    lines.push(...indentBlock(nested))
    lines.push(`${childIndent}],`)
  }
  lines.push(`${indent}},`)
  return lines
}

function collectReactNestedRouteLines(
  children: RouteNode[],
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
): string[] {
  const nested: string[] = []
  for (const child of children) {
    if (child.isGroup) {
      if (child.layoutPath) {
        nested.push(...emitReactLayoutRoute(child, ctx, imports, usedNames, indent))
      } else {
        nested.push(...collectReactNestedRouteLines(child.children, ctx, imports, usedNames, indent))
      }
    } else if (child.filePath) {
      nested.push(...emitReactNestedLeaf(child, ctx, imports, usedNames, indent))
    } else if (child.layoutPath) {
      nested.push(...emitReactLayoutRoute(child, ctx, imports, usedNames, indent))
    } else if (child.children.length) {
      nested.push(...emitReactDirectoryRoute(child, ctx, imports, usedNames, indent))
    }
  }
  return nested
}

function emitReactNestedLeaf(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
): string[] {
  return emitReactLeaf(node, ctx, imports, usedNames, indent)
}

function emitReactAbsoluteLeaf(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
): string[] {
  if (!node.filePath) return []
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = resolveImportMode(node, ctx.importMode) === 'lazy'
  const importPath = posixRelative(ctx.outFile, node.filePath)
  const isCatchAll = isCatchAllSegment(node.path ?? '') || node.isNotFound

  lines.push(`${indent}{`)
  if (isCatchAll) {
    lines.push(`${childIndent}path: ${JSON.stringify(reactCatchAllPath())},`)
  } else {
    lines.push(`${childIndent}path: ${JSON.stringify(node.urlPath === '/' ? '/' : node.urlPath)},`)
  }

  if (isLazy) {
    pushReactLazy(lines, childIndent, importPath, node.moduleExports, {
      hydrateFallbackId: reactHydrateFallbackId(ctx, node.loadingPath ?? null),
    })
  } else {
    const id = reactSyncNamedImports(node.filePath, node.moduleExports, imports, usedNames)
    lines.push(`${childIndent}Component: ${id},`)
    lines.push(...reactSyncModuleShorthand(node.moduleExports, childIndent))
  }

  const handle = formatReactHandle(node.meta, childIndent)
  if (handle) lines.push(handle)
  lines.push(`${indent}},`)
  return lines
}

function emitReactLeaf(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
): string[] {
  if (!node.filePath) return []
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = resolveImportMode(node, ctx.importMode) === 'lazy'
  const importPath = posixRelative(ctx.outFile, node.filePath)
  const isIndex = node.path === '' || node.path === null
  const isCatchAll = isCatchAllSegment(node.path ?? '')

  lines.push(`${indent}{`)

  if (isCatchAll) {
    lines.push(`${childIndent}path: ${JSON.stringify(reactCatchAllPath())},`)
  } else if (!isIndex && node.path) {
    lines.push(`${childIndent}path: ${JSON.stringify(node.path)},`)
  } else if (isIndex) {
    lines.push(`${childIndent}index: true,`)
  }

  if (isLazy) {
    pushReactLazy(lines, childIndent, importPath, node.moduleExports, {
      hydrateFallbackId: reactHydrateFallbackId(ctx, node.loadingPath ?? null),
    })
  } else {
    const id = reactSyncNamedImports(node.filePath, node.moduleExports, imports, usedNames)
    lines.push(`${childIndent}Component: ${id},`)
    lines.push(...reactSyncModuleShorthand(node.moduleExports, childIndent))
  }

  const handle = formatReactHandle(node.meta, childIndent)
  if (handle) lines.push(handle)

  lines.push(`${indent}},`)
  return lines
}

function wrapBaseRoute(lines: string[], baseRoute: string, indent: string): string[] {
  if (!baseRoute || lines.length === 0) return lines
  const childIndent = indent + '  '
  return [
    `${indent}{`,
    `${childIndent}path: ${JSON.stringify(baseRoute)},`,
    `${childIndent}children: [`,
    ...lines.map((l) => '  ' + l),
    `${childIndent}],`,
    `${indent}},`,
  ]
}

function withFallbackPaths(root: RouteNode, ctx: GenerateContext): GenerateContext {
  return {
    ...ctx,
    globalLoadingPath: ctx.globalLoadingPath ?? root.loadingPath,
    globalErrorPath: ctx.globalErrorPath ?? root.errorPath,
  }
}

export function generateReactRoutes(root: RouteNode, ctx: GenerateContext): string {
  const resolved = withFallbackPaths(root, ctx)
  const imports = new Map<string, ImportRef>()
  const usedNames = new Set<string>()
  const routeLines: string[] = []
  collectReactRoutes(root, resolved, imports, usedNames, '  ', routeLines)
  let finalLines = prettifyRouteBlocks(routeLines)
  if (resolved.baseRoute && !root.layoutPath) {
    finalLines = wrapBaseRoute(finalLines, resolved.baseRoute, '  ')
  }

  const fallbackImports = reactFallbackImportLines(resolved)
  const importLines: string[] = []
  for (const { id, filePath, isLazy, namedBindings } of imports.values()) {
    if (isLazy) continue
    const rel = posixRelative(ctx.outFile, filePath)
    if (namedBindings?.length) {
      importLines.push(
        `import { default as ${id}, ${namedBindings.join(', ')} } from '${rel}'`,
      )
    } else {
      importLines.push(`import ${id} from '${rel}'`)
    }
  }

  return [
    GENERATED_BANNER,
    ...fallbackImports,
    ...importLines,
    ...(fallbackImports.length || importLines.length ? [''] : []),
    ...routesFileTail(ctx, 'react', finalLines),
  ].join('\n')
}

function emitVueRouteBlockFields(node: RouteNode, indent: string): string[] {
  const block = node.routeBlock
  if (!block) return []
  const lines: string[] = []
  if (block.name) lines.push(`${indent}name: ${JSON.stringify(block.name)},`)
  if (block.alias) {
    const alias = Array.isArray(block.alias)
      ? `[${block.alias.map((a) => JSON.stringify(a)).join(', ')}]`
      : JSON.stringify(block.alias)
    lines.push(`${indent}alias: ${alias},`)
  }
  if (block.props !== undefined) {
    lines.push(
      `${indent}props: ${typeof block.props === 'boolean' ? block.props : JSON.stringify(block.props)},`,
    )
  }
  return lines
}

function vueResolvedPath(node: RouteNode): string {
  if (node.routeBlock?.path) {
    const p = node.routeBlock.path
    return p.startsWith('/') ? p : `/${p}`
  }
  return vueAbsolutePath(node)
}

function vueAbsolutePath(node: RouteNode): string {
  if (isCatchAllSegment(node.urlPath)) {
    // Vue Router 4+ catch-all syntax
    return '/:pathMatch(.*)*'
  }
  if (!node.urlPath || node.urlPath === '/') return '/'
  return node.urlPath.startsWith('/') ? node.urlPath : `/${node.urlPath}`
}

function collectVueRoutes(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  lines: string[],
  state: { usesDefineAsyncComponent: boolean },
): void {
  if (node.layoutPath) {
    lines.push(...emitVueLayoutRoute(node, ctx, imports, usedNames, indent, state))
    return
  }

  for (const child of node.children) {
    if (child.isGroup) {
      if (child.layoutPath) {
        lines.push(...emitVueLayoutRoute(child, ctx, imports, usedNames, indent, state))
      } else {
        collectVueRoutes(child, ctx, imports, usedNames, indent, lines, state)
      }
    } else if (child.layoutPath) {
      lines.push(...emitVueLayoutRoute(child, ctx, imports, usedNames, indent, state))
    } else if (child.filePath) {
      lines.push(...emitVueAbsoluteLeaf(child, ctx, imports, usedNames, indent, state))
    } else if (child.children.length > 0) {
      collectVueRoutes(child, ctx, imports, usedNames, indent, lines, state)
    }
  }
}

function emitVueDirectoryRoute(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  state: { usesDefineAsyncComponent: boolean },
): string[] {
  if (!node.path || !node.children.length) return []

  const solePage = node.children.length === 1 && node.children[0].filePath
    ? node.children[0]
    : null
  if (solePage && solePage.path && !solePage.layoutPath) {
    const combined = `${node.path}/${solePage.path}`
    return emitVueNestedLeaf({ ...solePage, path: combined }, ctx, imports, usedNames, indent, state)
  }

  const lines: string[] = []
  const childIndent = indent + '  '
  lines.push(`${indent}{`)
  lines.push(`${childIndent}path: ${JSON.stringify(node.path)},`)

  const nested = collectVueNestedRouteLines(node.children, ctx, imports, usedNames, childIndent, state)
  if (nested.length) {
    lines.push(`${childIndent}children: [`)
    lines.push(...indentBlock(nested))
    lines.push(`${childIndent}],`)
  }
  lines.push(`${indent}},`)
  return lines
}

function collectVueNestedRouteLines(
  children: RouteNode[],
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  state: { usesDefineAsyncComponent: boolean },
): string[] {
  const nested: string[] = []
  for (const child of children) {
    if (child.isGroup) {
      if (child.layoutPath) {
        nested.push(...emitVueLayoutRoute(child, ctx, imports, usedNames, indent, state))
      } else {
        nested.push(...collectVueNestedRouteLines(child.children, ctx, imports, usedNames, indent, state))
      }
    } else if (child.filePath) {
      nested.push(...emitVueNestedLeaf(child, ctx, imports, usedNames, indent, state))
    } else if (child.layoutPath) {
      nested.push(...emitVueLayoutRoute(child, ctx, imports, usedNames, indent, state))
    } else if (child.children.length) {
      nested.push(...emitVueDirectoryRoute(child, ctx, imports, usedNames, indent, state))
    }
  }
  return nested
}

function emitVueLayoutRoute(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  state: { usesDefineAsyncComponent: boolean },
): string[] {
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = ctx.importMode === 'lazy'

  lines.push(`${indent}{`)
  if (node.path) {
    lines.push(`${childIndent}path: ${JSON.stringify(node.path)},`)
  } else if (!indent.trim() || indent === '  ') {
    lines.push(`${childIndent}path: '/',`)
  }

  if (isLazy) {
    const component = vueComponentBody(
      posixRelative(ctx.outFile, node.layoutPath!),
      vueAsyncExtras(ctx, imports, usedNames, node.loadingPath, node.errorPath),
    )
    if (component.usesDefineAsyncComponent) state.usesDefineAsyncComponent = true
    pushMultilineField(lines, childIndent, 'component', component.lines)
  } else {
    const id = allocImport(node.layoutPath!, false, imports, usedNames)
    lines.push(`${childIndent}component: ${id},`)
  }

  const nested = collectVueNestedRouteLines(node.children, ctx, imports, usedNames, childIndent, state)
  if (nested.length) {
    lines.push(`${childIndent}children: [`)
    lines.push(...indentBlock(nested))
    lines.push(`${childIndent}],`)
  }
  lines.push(`${indent}},`)
  return lines
}

function emitVueNestedLeaf(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  state: { usesDefineAsyncComponent: boolean },
): string[] {
  if (!node.filePath) return []
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = resolveImportMode(node, ctx.importMode) === 'lazy'
  const importPath = posixRelative(ctx.outFile, node.filePath)
  const isIndex = !node.path || node.path === ''
  const isCatchAll = isCatchAllSegment(node.path ?? '')

  lines.push(`${indent}{`)
  if (isCatchAll) {
    lines.push(`${childIndent}path: ':pathMatch(.*)*',`)
  } else if (isIndex) {
    lines.push(`${childIndent}path: '',`)
  } else {
    lines.push(`${childIndent}path: ${JSON.stringify(node.path)},`)
  }

  if (isLazy) {
    const component = vueComponentBody(
      importPath,
      vueAsyncExtras(ctx, imports, usedNames),
    )
    if (component.usesDefineAsyncComponent) state.usesDefineAsyncComponent = true
    pushMultilineField(lines, childIndent, 'component', component.lines)
  } else {
    const id = allocImport(node.filePath, false, imports, usedNames)
    lines.push(`${childIndent}component: ${id},`)
  }

  lines.push(...emitVueRouteBlockFields(node, childIndent))
  const meta = formatVueMeta(node.meta, childIndent)
  if (meta) lines.push(meta)
  lines.push(`${indent}},`)
  return lines
}

function emitVueAbsoluteLeaf(
  node: RouteNode,
  ctx: GenerateContext,
  imports: Map<string, ImportRef>,
  usedNames: Set<string>,
  indent: string,
  state: { usesDefineAsyncComponent: boolean },
): string[] {
  if (!node.filePath) return []
  const lines: string[] = []
  const childIndent = indent + '  '
  const isLazy = resolveImportMode(node, ctx.importMode) === 'lazy'
  const importPath = posixRelative(ctx.outFile, node.filePath)

  lines.push(`${indent}{`)
  lines.push(`${childIndent}path: ${JSON.stringify(vueResolvedPath(node))},`)

  if (isLazy) {
    const component = vueComponentBody(
      importPath,
      vueAsyncExtras(ctx, imports, usedNames),
    )
    if (component.usesDefineAsyncComponent) state.usesDefineAsyncComponent = true
    pushMultilineField(lines, childIndent, 'component', component.lines)
  } else {
    const id = allocImport(node.filePath, false, imports, usedNames)
    lines.push(`${childIndent}component: ${id},`)
  }

  lines.push(...emitVueRouteBlockFields(node, childIndent))
  const meta = formatVueMeta(node.meta, childIndent)
  if (meta) lines.push(meta)
  lines.push(`${indent}},`)
  return lines
}

export function generateVueRoutes(root: RouteNode, ctx: GenerateContext): string {
  const resolved = withFallbackPaths(root, ctx)
  const imports = new Map<string, ImportRef>()
  const usedNames = new Set<string>()
  const routeLines: string[] = []
  const state = { usesDefineAsyncComponent: false }
  collectVueRoutes(root, resolved, imports, usedNames, '  ', routeLines, state)
  let finalLines = prettifyRouteBlocks(routeLines)
  if (resolved.baseRoute && !root.layoutPath) {
    finalLines = wrapBaseRoute(finalLines, resolved.baseRoute, '  ')
  }

  const importLines: string[] = []
  for (const { id, filePath, isLazy } of imports.values()) {
    if (!isLazy) {
      importLines.push(`import ${id} from '${posixRelative(ctx.outFile, filePath)}'`)
    }
  }

  return [
    GENERATED_BANNER,
    ...(state.usesDefineAsyncComponent ? [`import { defineAsyncComponent } from 'vue'`, ''] : []),
    ...importLines,
    ...(importLines.length ? [''] : []),
    ...routesFileTail(ctx, 'vue', finalLines),
  ].join('\n')
}
